/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MedVault } from './MedVault.js';
export * as factories from './factories/index.js';
export { MedVault__factory } from './factories/MedVault__factory.js';