/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace MedVault {
      
    export type MedicalRecordStruct = {id: BigNumberish, ipfsHash: string, title: string, timestamp: BigNumberish, isDeleted: boolean}

    export type MedicalRecordStructOutput = [id: bigint, ipfsHash: string, title: string, timestamp: bigint, isDeleted: boolean] & {id: bigint, ipfsHash: string, title: string, timestamp: bigint, isDeleted: boolean }
  
    }

  export interface MedVaultInterface extends Interface {
    getFunction(nameOrSignature: "addMedicalRecord" | "checkAccessClearance" | "deleteRecord" | "getMyAuthorizedDoctors" | "getMyRecords" | "getPatientRecordsAsDoctor" | "grantAccessToDoctor" | "isRegistered" | "registerRole" | "registerUser" | "revokeAccessFromDoctor" | "systemOwner" | "userRoles" | "verifyPractitioner"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AccessGranted" | "AccessRevoked" | "PractitionerVerified" | "RecordAdded" | "RecordDeleted" | "RoleRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'addMedicalRecord', values: [string, string]): string;
encodeFunctionData(functionFragment: 'checkAccessClearance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'deleteRecord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMyAuthorizedDoctors', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMyRecords', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPatientRecordsAsDoctor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantAccessToDoctor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerRole', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerUser', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeAccessFromDoctor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'systemOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'userRoles', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifyPractitioner', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addMedicalRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkAccessClearance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deleteRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMyAuthorizedDoctors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMyRecords', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPatientRecordsAsDoctor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantAccessToDoctor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeAccessFromDoctor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'systemOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userRoles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyPractitioner', data: BytesLike): Result;
  }

  
    export namespace AccessGrantedEvent {
      export type InputTuple = [patient: AddressLike, doctor: AddressLike];
      export type OutputTuple = [patient: string, doctor: string];
      export interface OutputObject {patient: string, doctor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AccessRevokedEvent {
      export type InputTuple = [patient: AddressLike, doctor: AddressLike];
      export type OutputTuple = [patient: string, doctor: string];
      export interface OutputObject {patient: string, doctor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PractitionerVerifiedEvent {
      export type InputTuple = [doctor: AddressLike, verifier: AddressLike];
      export type OutputTuple = [doctor: string, verifier: string];
      export interface OutputObject {doctor: string, verifier: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordAddedEvent {
      export type InputTuple = [patient: AddressLike, recordId: BigNumberish, ipfsHash: string];
      export type OutputTuple = [patient: string, recordId: bigint, ipfsHash: string];
      export interface OutputObject {patient: string, recordId: bigint, ipfsHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordDeletedEvent {
      export type InputTuple = [patient: AddressLike, recordId: BigNumberish];
      export type OutputTuple = [patient: string, recordId: bigint];
      export interface OutputObject {patient: string, recordId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRegisteredEvent {
      export type InputTuple = [user: AddressLike, role: BigNumberish];
      export type OutputTuple = [user: string, role: bigint];
      export interface OutputObject {user: string, role: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MedVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): MedVault;
    waitForDeployment(): Promise<this>;

    interface: MedVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addMedicalRecord: TypedContractMethod<
      [_ipfsHash: string, _title: string, ],
      [void],
      'nonpayable'
    >
    

    
    checkAccessClearance: TypedContractMethod<
      [_patient: AddressLike, _doctor: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    deleteRecord: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getMyAuthorizedDoctors: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getMyRecords: TypedContractMethod<
      [],
      [MedVault.MedicalRecordStructOutput[]],
      'view'
    >
    

    
    getPatientRecordsAsDoctor: TypedContractMethod<
      [_patientAddress: AddressLike, ],
      [MedVault.MedicalRecordStructOutput[]],
      'view'
    >
    

    
    grantAccessToDoctor: TypedContractMethod<
      [_doctor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isRegistered: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    registerRole: TypedContractMethod<
      [_role: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registerUser: TypedContractMethod<
      [_userAddress: AddressLike, _role: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeAccessFromDoctor: TypedContractMethod<
      [_doctor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    systemOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    userRoles: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    verifyPractitioner: TypedContractMethod<
      [_pendingDoctor: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addMedicalRecord'): TypedContractMethod<
      [_ipfsHash: string, _title: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkAccessClearance'): TypedContractMethod<
      [_patient: AddressLike, _doctor: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'deleteRecord'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getMyAuthorizedDoctors'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getMyRecords'): TypedContractMethod<
      [],
      [MedVault.MedicalRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPatientRecordsAsDoctor'): TypedContractMethod<
      [_patientAddress: AddressLike, ],
      [MedVault.MedicalRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'grantAccessToDoctor'): TypedContractMethod<
      [_doctor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerRole'): TypedContractMethod<
      [_role: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerUser'): TypedContractMethod<
      [_userAddress: AddressLike, _role: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeAccessFromDoctor'): TypedContractMethod<
      [_doctor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'systemOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'userRoles'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'verifyPractitioner'): TypedContractMethod<
      [_pendingDoctor: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AccessGranted'): TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
getEvent(key: 'AccessRevoked'): TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
getEvent(key: 'PractitionerVerified'): TypedContractEvent<PractitionerVerifiedEvent.InputTuple, PractitionerVerifiedEvent.OutputTuple, PractitionerVerifiedEvent.OutputObject>;
getEvent(key: 'RecordAdded'): TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
getEvent(key: 'RecordDeleted'): TypedContractEvent<RecordDeletedEvent.InputTuple, RecordDeletedEvent.OutputTuple, RecordDeletedEvent.OutputObject>;
getEvent(key: 'RoleRegistered'): TypedContractEvent<RoleRegisteredEvent.InputTuple, RoleRegisteredEvent.OutputTuple, RoleRegisteredEvent.OutputObject>;

    filters: {
      
      'AccessGranted(address,address)': TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
      AccessGranted: TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
    

      'AccessRevoked(address,address)': TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
      AccessRevoked: TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
    

      'PractitionerVerified(address,address)': TypedContractEvent<PractitionerVerifiedEvent.InputTuple, PractitionerVerifiedEvent.OutputTuple, PractitionerVerifiedEvent.OutputObject>;
      PractitionerVerified: TypedContractEvent<PractitionerVerifiedEvent.InputTuple, PractitionerVerifiedEvent.OutputTuple, PractitionerVerifiedEvent.OutputObject>;
    

      'RecordAdded(address,uint256,string)': TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
      RecordAdded: TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
    

      'RecordDeleted(address,uint256)': TypedContractEvent<RecordDeletedEvent.InputTuple, RecordDeletedEvent.OutputTuple, RecordDeletedEvent.OutputObject>;
      RecordDeleted: TypedContractEvent<RecordDeletedEvent.InputTuple, RecordDeletedEvent.OutputTuple, RecordDeletedEvent.OutputObject>;
    

      'RoleRegistered(address,uint8)': TypedContractEvent<RoleRegisteredEvent.InputTuple, RoleRegisteredEvent.OutputTuple, RoleRegisteredEvent.OutputObject>;
      RoleRegistered: TypedContractEvent<RoleRegisteredEvent.InputTuple, RoleRegisteredEvent.OutputTuple, RoleRegisteredEvent.OutputObject>;
    
    };
  }